name: 'CI'

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: [flyci-macos-14-m2, wingman]
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v4

      - name: Make a failure
        run: exit 1
